### ISSUE TITLE
Documentation about message versioning strategy

### ISSUE THREAD

**Issue by thiloplanz** [devsisters/shardcake#10]
What are the options for evolving the messages that entities can process, in particular with regards to how to roll that out (with downtime or online)?

From the architecture overview, it looks like

- messages are not persisted (just used for network calls), so if you can shut down the whole system and reboot with a new version, any kind of changes are possible
- for rolling upgrades, you'd need to be in some state where new messages can be defined in code already, but as long as they are not used, the older version of the protocol still needs to be able to read the older messages sent by the new protocol. After every pod has been upgraded to the new version of the code, you can start using the new messages.
- from the looks of it, adding new entity types and new message case classes should work regardless of serialization method (as well as deleting entities and case classes)
- you can have different version of the pods specify different entities as being available in it in pretty much any combination, which should help here
- adding new fields to existing case classes with provided default or as optional fields may work depending on the serialization method. How does Kryo behave in this regard? If you add an optional field to a case class, can it still handle messages from the earlier version that does include it?

**Comment by ghostdogpr** [comment]
You're totally right! For rolling updates it really depends on the serialization implementation. There are some solutions that support more or less modifications. Kryo by default is pretty strict and won't support most changes, but there are settings to support more (at the cost of some performance or message size), see https://github.com/EsotericSoftware/kryo

With shardcake we wanted to be as flexible as possible for users so we don't force using one in particular. We provided the Kryo one because it's the one we use in prod but anything is possible by just implementing a simple trait.

**Comment by ghostdogpr** [comment]
(I'll add the points you mentioned to the docs) 🙏

**Comment by ghostdogpr** [comment]
Closed by https://github.com/devsisters/shardcake/commit/c0589e7d252e816c14a4f4389ecd1d32f7850aea
