### ISSUE TITLE
`sendStreamAndReceiveStream(...).interruptWhen(...)` blocks the sending stream in the middle in certain conditions

### ISSUE THREAD

**Issue by nedsociety** [devsisters/shardcake#133]
Currently I've encountered a case of

```scala
// takeQueue: Queue[Take[Nothing, ?]], contents offered from another fiber

sendStreamAndReceiveStream(
 ZStream.succeed(somePremises...) ++ ZStream.fromQueue(takeQueue).flattenTake
).interruptWhen(totallyUnrelatedPromiseOrZio)
```

Which would only send `somePremises` and then indefinitely block sending the content from `takeQueue`. It doesn't matter if `totallyUnrelatedPromiseOrZio` is signaled (/ended) or not. Merely setting `.interruptWhen()` on the output stream causes the bug.

MCVE incoming next week. Will try fixing after that.

**Comment by ghostdogpr** [comment]
After looking at a reproducer, I'm convinced the issue is in ZIO, not in Shardcake. The simple fact that adding `interruptWhen` with a promise that never completes changes the behavior is wrong. In fact, it looks very similar to https://github.com/zio/zio/issues/7460. Let's open a ZIO issue after we have an isolated reproducer.
